// Generated by CoffeeScript 1.3.3
(function() {
  var JsReplApp;

  window.log = function() {
    if (this.console) {
      console.log(Array.prototype.slice.call(arguments));
    }
  };

  JsReplApp = (function() {

    JsReplApp.prototype.doEval = function() {
      var hp, inp, jsonres, out, res, snip;
      inp = $("#inp-expr");
      inp.removeClass("dimmed");
      snip = inp.val();
      inp.val("");
      log("evaluating", snip);
      res = "";
      try {
        res = eval(snip);
      } catch (e) {
        res = "Error: " + e;
      }
      try {
        jsonres = JSON.stringify(res);
      } catch (e2) {
        jsonres = res.toString();
      }
      hp = $("#historypanel");
      out = this.res_template({
        inputval: snip,
        outputval: jsonres
      });
      return hp.prepend(out);
    };

    JsReplApp.prototype.bindEvents = function() {
      var _this = this;
      return $("#btn-execute").on("click", function() {
        log("button clicked");
        return _this.doEval();
      });
    };

    JsReplApp.prototype.start = function() {
      log("startup");
      return this.bindEvents();
    };

    function JsReplApp() {
      var tmpl;
      tmpl = "<div class=\"historyentry\">\n    <div class=\"in\"><%- inputval %></div>\n    <div class=\"out\"><%- outputval %></div>\n</div>";
      this.res_template = _.template(tmpl);
      0;

    }

    JsReplApp.prototype.initialize = function() {
      return 0;
    };

    return JsReplApp;

  })();

  window.jsreplapp = new JsReplApp;

  $(function() {
    return app.start();
  });

}).call(this);
